### PR TITLE
Add FreeBSD platform

### PR DESCRIPTION
**Pull request by freqlabs**

### CODE REVIEW

**Comment by wdanilo** [comment]
Hi! First of all, thank you for your pull request. I've got several questions:

1. Are you porting Luna to FreeBSD? If so, what is the progress? I would like to help with any problem you encounter!
2. Isn't FreeBSD just a distribution of the BSD family? Shouldn't we then name it `BSD` instead of `FreeBSD`?

**Comment by freqlabs** [comment]
1. I wanted to try Luna on my FreeBSD machine. After adding these changes, the code builds and runs fine. I have tested a simple hello world program. :smiley: Is there a more comprehensive set of tests I can run?

2. Each of the major BSD variants is a distinct OS with its own kernel, libraries, and utilities. They are not distributions of mostly the same software as in Linux. I choose the name `FreeBSD` based on this fact and to follow the naming of the macro definitions from `ghcplatform.h`

**Comment by kustosz** [comment]
@freqlabs thank you for the contribution, it looks good to merge. Could you accept our CLA at https://cla-assistant.io/luna/luna?pullRequest=108 before we merge?

**Comment by freqlabs** [comment]
Done :)

**Comment by kustosz** [comment]
Thanks, merged! :)

**Comment by wdanilo** [comment]
@freqlabs good work, thank you!

**Pull request merged**
