### PR TITLE
Suggested clarification about compiler options

### PR DESCRIPTION
**Pull request by samuell**
Is this what is intended? The previous sentence seemed self-contradictory

### CODE REVIEW

**Comment by pmlodawski** [comment]
You are right that this paragraph may not be clear. I think we can change it as follows:

> Additionally, if you intend to simply use the **Luna** compiler (as opposed to tinkering with it, which requires frequent rebuilds), you may consider adding `--ghc-options="-O2 -j4"` to the `stack install` command. This should make the **Luna** compiler run considerably faster, at the cost of longer build times.

**Comment by samuell** [comment]
Ok, well I don't see how running the compiler faster, leads to longer build times? :) ... but I'm probably just not aquainted enough with the toolchain ...

**Comment by samuell** [comment]
Aha, well ... longer build time to build the luna compiler that is?

**Comment by samuell** [comment]
If so, perhaps change:

"cost of longer build times."

to

"cost of longer build times, for building the Luna compiler."

?

**Comment by pmlodawski** [comment]
Exactly, "cost of longer build times, for building the Luna compiler".

**Comment by wdanilo** [comment]
Thanks for fixing it @samuell !

**Comment by samuell** [comment]
Hi @wdanilo Sorry, I think together with @pmlodawski we realized I had also misunderstood the sentence slightly, and we should have done more edits, which weren't included in this patch. Will see if I can add them as another commit ...

**Comment by samuell** [comment]
@wdanilo Sent the fix in a separate PR: #98

**Pull request merged**
