### PR TITLE
Lquery Integration

### PR DESCRIPTION
**Pull request by mwu-tow**
### Pull Request Description

LQuery language, as specified in https://github.com/luna/Dataframes/issues/9 with minor adjustments. 

### Important Notes

Please refer to https://github.com/luna/Dataframes/issues/9 for details

### Checklist
Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] The code conforms to the [Luna Style Guide](https://github.com/luna/wiki/blob/master/code-style/01.general.md).
- [x] The code has been tested where possible.

### CODE REVIEW

**Comment by iamrecursion** [comment]
I don't like the idea of adding _another_ top-level folder in the repo. Is there a better place for `resources/`?

**Comment by iamrecursion** [comment]
As for names, I'm wondering if we could find something based on the roman goddess Luna.

**Comment by mwu-tow** [comment]
@sylwiabr Do we need the `resources` here? I don't think they are related to the LQuery changes.

**Comment by sylwiabr** [comment]
I was just doing luna appimage with this branch and push it here. It is unrelated to `LQuery` @mwu-tow  @iamrecursion If we decide to change the place for resources we have to change it in luna-studio as well and fix a path in luna-manager.

**Comment by iamrecursion** [comment]
Can't we keep these resources in the luna-manager repo?

**Comment by wdanilo** [comment]
I' thinking about better name. It would be helpful if we summarize what this library aims to do in a perspective of year or two. What is it's goal in longer perspective?

**Comment by sylwiabr** [comment]
The `resources` folder was deleted from this PR, I will create a new one for this. The names we can change later. Just let's keep it in mind. I am merging the PR after a quick talk with @wdanilo and @lgawlik

**Comment by mwu-tow** [comment]
I've opened #287 so the discussion on name can be continued there.

**Pull request merged**
